### ISSUE TITLE
CMEDatabase instance has no attribute 'get_computers'

### ISSUE THREAD

**Issue by stickyicky90** [Hackndo/lsassy#10]
I am receiving the following error when attempting to use the CME module, please advise. 
![image](https://user-images.githubusercontent.com/59264206/71488470-ae686b80-27ee-11ea-9080-927ab9d43e1a.png)

**Comment by Hackndo** [comment]
Hello !
CrackMapExec needs to be up to date (min v4)
I added this information in https://github.com/Hackndo/lsassy/blob/master/cme/README.md
Thanks :)

**Comment by stickyicky90** [comment]
Thank you!
