### ISSUE TITLE
pipenv shell

### ISSUE THREAD

**Issue by bucky67gto** [Hackndo/lsassy#12]
Not sure if running in pipenv shell is the issue, but getting the error after a successful dump of lsass.exe:

Detailed error : /bin/sh: 1: lsassy: not found

Thoughts?

**Comment by bucky67gto** [comment]
quick update.  copied the lsassy directory to the /bin and gave full rights.  now error changed to:

Detailed error : /bin/sh: 1: lsassy:  Permission denied

I verified that all have access and execute to this directory.....the plot thickens

**Comment by mpgn** [comment]
maybe `pip install lsassy --user` ?

**Comment by bucky67gto** [comment]
thanks for the try, but no go. same error, but i did not need to move any files this time.

**Comment by Hackndo** [comment]
You need to make sure that lsassy is in the correct python path when running your script.
```python
import sys
sys.path
```
Check that lsassy is somewhere in this path

**Comment by Hackndo** [comment]
I close this issue as it's not related to lsassy.
