### ISSUE TITLE
Add export feature

### ISSUE THREAD

**Issue by mpgn** [Hackndo/lsassy#26]
Add an export feature that allows an export of the credentials found with lsassy into a file.

Exemple
```
lsassy adsec.local/jsnow:pass@dc01.adsec.local --export /tmp/my_export
```

Where my_export contains:
```
machine[TAB]domain\user[TAB]hash[TAB]cleartext
machine[TAB]machine\user[TAB]hash[TAB]cleartext
```

why tabulations as delimiter ? To avoid problem since a cleartext password can contains special char.

**Comment by Hackndo** [comment]
Coming in next version

**Comment by ITPPA** [comment]
agreed

**Comment by Hackndo** [comment]
Live now !
https://github.com/Hackndo/lsassy/wiki/Lsassy-Advanced-Usage#save-in-a-file
