### ISSUE TITLE
Using lsassy on Ubuntu WSL

### ISSUE THREAD

**Issue by NtHawk101** [Hackndo/lsassy#29]
**Describe the bug**
Maybe not so much a bug as a desire to see if it would run in WSL. Thinking Windows store apps can be accessed by non-admin users and then install Ubuntu along with lsassy. Should this be a pull request? A little new to the game here but testing my limits.

**Expected behavior**
Here are my steps:
Install WSL on Win10 device
Install Ubuntu from Windows store
Check if Python3 is installed
	python3 --version
Install Python 3 (if needed)
	sudo apt install python3
Update apt-get
	sudo apt-get update
Install netaddr
	sudo apt-get install -y python-netaddr
	Pip3 install netaddr
Install pip3
	sudo apt-get install python3-pip
Install pypykatz
	pip3 install pypykatz
Clone Impacket
	sudo git clone https://github.com/SecureAuthCorp/impacket.git
	cd impacket/
	sudo python3 setup.py install
Install lsassy
sudo python3.6 -m pip install lsassy 

**Screenshots**

**Additional context**
The command and results
user@computer:/$ lsassy domain/%username%:%Password%@%FQDN_deviceName
Traceback (most recent call last):
  File "/usr/local/bin/lsassy", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/lsassy/core.py", line 208, in run
    targets = get_targets(get_args().target)
  File "/usr/local/lib/python3.6/dist-packages/lsassy/utils/utils.py", line 134, in get_targets
    ret_targets += parse_targets(target)
  File "/usr/local/lib/python3.6/dist-packages/lsassy/utils/utils.py", line 101, in parse_targets
    t = IPRange(ip_range[0], ip_range[1])
  File "/usr/local/lib/python3.6/dist-packages/netaddr/ip/__init__.py", line 1357, in __init__
    self._start = IPAddress(start, flags=flags)
  File "/usr/local/lib/python3.6/dist-packages/netaddr/ip/__init__.py", line 280, in __init__
    % self.__class__.__name__)
ValueError: IPAddress() does not support netmasks or subnet prefixes! See documentation for details.

**Comment by Hackndo** [comment]
hey there, it looks like you're using old lsassy syntax. It has been updated in v2. Please check this for more info
```
lsassy -h
```
Let me know if that solves your issue :)

**Comment by Hackndo** [comment]
By the way, lsassy should work in a cmd.exe console =)

**Comment by NtHawk101** [comment]
Funny, that worked but now I have questions.
If there is an exclamation point in the password, it throws an error stating event not found.
Maybe one way that breaks this vuln? lol

**Comment by Hackndo** [comment]
That's because of **bash** ;)
https://unix.stackexchange.com/a/3748/126403
