### ISSUE TITLE
Work with SOCKS proxies, add a `-no-pass` option

### ISSUE THREAD

**Issue by ShutdownRepo** [Hackndo/lsassy#42]
When relaying NTLM authentications, [ntlmrelayx.py](https://github.com/SecureAuthCorp/impacket/blob/master/examples/ntlmrelayx.py) has the ability to open SOCKS proxies, hence allowing other scripts like secretsdump, psexec and so on to do their things via these proxies. It could be nice to add this feature to lsassy.

In addition to that, some impacket script have the `-no-pass` option allowing to connect through those proxies without having to enter a password or hash, since the authentication has already happened when relaying.

I don't think I'd have the time or ability to add this feature to lsassy so here you go :)

**Comment by Hackndo** [comment]
That's an interesting feature. When I have some time, I'll look into it

**Comment by Hackndo** [comment]
Added in 3.0.0
