### ISSUE TITLE
Error while executing lsassy

### ISSUE THREAD

**Issue by Th3-GuArdiaN** [Hackndo/lsassy#43]
![image](https://user-images.githubusercontent.com/53962717/79308913-fe994400-7f2b-11ea-965b-75398b49c4de.png)

![image](https://user-images.githubusercontent.com/53962717/79308960-1244aa80-7f2c-11ea-9b8f-5a095b48e01b.png)
The firewall is off

**Comment by Hackndo** [comment]
Hello,
Which version of CME are you using?

**Comment by Th3-GuArdiaN** [comment]
Version: 4.0.1dev

**Comment by Hackndo** [comment]
And what version of lsassy?

**Comment by Hackndo** [comment]
Please check if https://github.com/Hackndo/lsassy/releases/tag/v2.1.2 fixes your issue (although I couldn't reproduce it)
Also note that lsassy can be use as a standalone tool.

```python
lsassy -d 'lab.local' -u 'Administrator' -p 'Password1' 192.168.0.5
```

**Comment by Th3-GuArdiaN** [comment]
Your updated fixed my problem... but now i got the "lsass is protected" even with the firewall turned off.. im trying it on Windows server 2019... works fine on windows 10

**Comment by Hackndo** [comment]
That's another issue. Please open an issue if necessary, **with details** ;)
