### ISSUE TITLE
issues 

### ISSUE THREAD

**Issue by isarabia92** [Hackndo/lsassy#5]
Hello Hackndo,
Thanks for this amazing tool, i've tried to combine lsassy to cme using this command "cme  smb 192.168.2.0/24  -u Administrateur -p P@ssword@2019 -M lsassy -o PROCDUMP_PATH='/tmp/' PROCDUMP_EXE_NAME='procdump64.exe' " , unfortunately i get some error you will find it below 

![image](https://user-images.githubusercontent.com/7432174/70718776-2021bf00-1cf1-11ea-8765-c4f54088bed9.png)

Do you have some suggestions

**Comment by Hackndo** [comment]
Hello,
As suggested, please attach the `--verbose` output of crackmapexec to your issue :)

```
cme smb --verbose 192.168.2.0/24 -u Administrateur -p P@ssword@2019 -M lsassy -o PROCDUMP_PATH='/tmp/' PROCDUMP_EXE_NAME='procdump64.exe' 
```

Thanks !

**Comment by isarabia92** [comment]
Hello ,
Thanks for your reply , here is the issue 
![image](https://user-images.githubusercontent.com/7432174/70730591-90d2d680-1d05-11ea-9feb-2181794b621d.png)

**Comment by Hackndo** [comment]
Be sure to use the last version of the tool, as this issue was fixed here https://github.com/Hackndo/lsassy/commit/d33529349979fe87b5b418297523061f49e7a92c
:)
