### ISSUE TITLE
[Feature Request] Add smbexec-style execution method to lsassy

### ISSUE THREAD

**Issue by Invoke-Mimikatz** [Hackndo/lsassy#51]
Lsassy currently only supports wmi and task exec methods. Wmi does not work through an ntlmrelayx socks proxy, and the task exec method seems flaky at best when run through a proxy. Adding an SMB execution method would allow lsassy to be run through relayed SMB sessions.

**Comment by Hackndo** [comment]
Added in 3.0.0 :)
