### ISSUE TITLE
Scheduled Task 

### ISSUE THREAD

**Issue by OffenseTeacher** [Hackndo/lsassy#58]
Hi,

Is there a reason the scheduled task is scheduled to run every day at the same hour? From my understanding, it should run only once and on demand. In case the scheduled task fails to get deleted, it will dump lsass for eternity.

File: https://github.com/Hackndo/lsassy/blob/master/lsassy/exec/taskexe.py

Code:
`

&lt;Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task"&gt;  &lt;Triggers&gt;    &lt;CalendarTrigger&gt;      &lt;StartBoundary&gt;2015-07-15T20:35:13.2757294&lt;/StartBoundary&gt;      &lt;Enabled&gt;true&lt;/Enabled&gt;      &lt;ScheduleByDay&gt;        &lt;**_DaysInterval&gt;1&lt;/DaysInterval_**&gt;

`

Thanks :)

**Comment by Hackndo** [comment]
Hey there,
Please use branch 3.0.0, here it only executes once. https://www.github.com/Hackndo/lsassy/tree/3.0.0/lsassy%2Fexec%2Ftask.py
I might update master someday also (or you could PR if you in a rush)
Thanks!

**Comment by Hackndo** [comment]
https://github.com/Hackndo/lsassy/pull/54

**Comment by Hackndo** [comment]
Ok I fixed it on master, and published a new release with this fix and other minor fixes.
