### ISSUE TITLE
Feature Request - Turn off deleting LSASS dmp

### ISSUE THREAD

**Issue by barrett092** [Hackndo/lsassy#67]
Is there a way to prevent the script from deleting the LSASS dmp during script execution during cleanup?

**Comment by Hackndo** [comment]
Hello,
Not at the moment, no. Would you like this option? What would be the use case?

**Comment by barrett092** [comment]
I could be wayyyy off but if the LSASS dump file has data in it, it can
potentially be parsed. So if for whatever reason the remote parsing fails
but a user has RDP or SMB access to the host, they can go in and copy the
dump file back to the attacking host.
Like I said I could be way off.

**Comment by Hackndo** [comment]
Thank you for the idea. Added to 3.1.2
