### ISSUE TITLE
EDRSandblast: use both --usermode & --kernelmode options

### ISSUE THREAD

**Issue by themaks** [Hackndo/lsassy#68]
https://github.com/Hackndo/lsassy/blob/f72eeb9eeeb22a37d6c94c6460fe7740e5e709ae/lsassy/dumpmethod/edrsandblast.py#L44

Hello Pixis (and potential EDRSandblast users),

I recommend to use both `--usermode` and `--kernelmode` options (the former does not imply the latter). 

Since loading a driver is needed for the kernel land bypasses to take place, and `NtLoadDriver` syscall might be hooked in userland, using both options reduces the risk of detection ;)

cheers

**Comment by themaks** [comment]
(only since https://github.com/wavestone-cdt/EDRSandblast/commit/3c81bd4f26bda8e81fb79df1750bd6553d9902b6 we load the driver AFTER userland unhooking has taken place)

**Comment by mpgn** [comment]
good catch
