### ISSUE TITLE
$ in password

### ISSUE THREAD

**Issue by Bl4d3666** [Hackndo/lsassy#8]
Seem to be an issue when you have a $ in the password.
Command
`cme --verbose smb 192.168.100.100 -u 'Admin' -p 'Password$' -d oliverhume -M lsassy`

Error Message the @ has gone missing.

`Domain/Admin:Password192.168.100.100:/C$/Windows/Temp//tmp.dmp is not valid. Expected format : [domain/]username[:password]@host:/share_name/path/to/file`

**Comment by Hackndo** [comment]
Thanks for this issue ! Since CME is py2 only, I have to create a command line with lsassy, and the parameters were not between quotes so the $ sign was interpreted in that CLI.

Should be fixed with that commit.
