### ISSUE TITLE
 packaging issue: deployment of tests

### ISSUE THREAD

**Issue by noraj** [Hackndo/lsassy#84]
The issue is that the setup.py is deploying the `tests` folder under the root python path and not under this package one.

So it's end up under `/usr/lib/python3.11/site-packages/tests` rather than `/usr/lib/python3.11/site-packages/lsassy /tests` and so conflicts with other packages having the same issue.

Anyway usually test are not shipped in a release package so the easiest would just to remove them. Else they should be deployed in the children directory. 

It's explained in ArchLinux packaging guidelines for Python: https://wiki.archlinux.org/title/Python_package_guidelines#Test_directory_in_site-package

**Comment by Hackndo** [comment]
Thanks :)
