### ISSUE TITLE
Kerberos Ticket Dump Enhancement

### ISSUE THREAD

**Issue by Cyb3rC3lt** [Hackndo/lsassy#86]
## Version(s)

* lsassy : version 3.1.8
* CME : version 6

## Describe the Enhancement

As discussed it would be pretty useful if we could see the expiry datetime of the Kirbi tickets, potentially in their filename if not too long. Also in a universal date format, not with month before the day which is confusing for non-Americans :-). These tickets are generated from this command:

`lsassy 192.168.32.131 -u Administrator -p Password1 --users -K tickets -dc-ip 192.168.32.131`

This would help us priortise which ones are ending soonest and also allow us to pick and choose which ones we want to convert to a ccache file.

Current filenames:

![image](https://github.com/Hackndo/lsassy/assets/33097451/fa962be1-8395-4281-b128-7ee93d9ed1f1)

**Comment by Hackndo** [comment]
Could you try branch 3.1.9 (especially https://github.com/Hackndo/lsassy/commit/f088fedd159a776cacbf8e1146fd730f2116a247) ?

**Comment by Cyb3rC3lt** [comment]
Thank you, that looks to be working now. Very quick turnaround. For anyone else reading this the date is in the format:
"YEAR MONTH DAY HOUR MINUTE SECOND"

![image](https://github.com/Hackndo/lsassy/assets/33097451/44948bd0-0152-4539-94ce-ebde4719f4bc)
